name: Works with Zig 0.11.0
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build-zigredis:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Check zig version
        run: zig version
      - name: Run zigredis tests
        run: cd zigredis && zig build test
      - name: run zigcaskdb tests
        run: cd zig-caskdb && zig build test
